config/routes.rb
SimpleScaffoldReference::Application.routes.draw do
  resources :snacks

end

app/models/snack.rb
class Snack < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  # GET /snacks
  # GET /snacks.xml
  def index
    @snacks = Snack.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @snacks }
    end
  end

  # GET /snacks/1
  # GET /snacks/1.xml
  def show
    @snack = Snack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @snack }
    end
  end

  # GET /snacks/new
  # GET /snacks/new.xml
  def new
    @snack = Snack.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @snack }
    end
  end

  # GET /snacks/1/edit
  def edit
    @snack = Snack.find(params[:id])
  end

  # POST /snacks
  # POST /snacks.xml
  def create
    @snack = Snack.new(params[:snack])

    respond_to do |format|
      if @snack.save
        format.html { redirect_to(@snack, :notice => 'Snack was successfully created.') }
        format.xml  { render :xml => @snack, :status => :created, :location => @snack }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @snack.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /snacks/1
  # PUT /snacks/1.xml
  def update
    @snack = Snack.find(params[:id])

    respond_to do |format|
      if @snack.update_attributes(params[:snack])
        format.html { redirect_to(@snack, :notice => 'Snack was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @snack.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /snacks/1
  # DELETE /snacks/1.xml
  def destroy
    @snack = Snack.find(params[:id])
    @snack.destroy

    respond_to do |format|
      format.html { redirect_to(snacks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleScaffoldReference</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snacks/_form.html.erb
<%= form_for(@snack) do |f| %>
  <% if @snack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snack.errors.count, "error") %> prohibited this snack from being saved:</h2>

      <ul>
      <% @snack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :healthy %><br />
    <%= f.check_box :healthy %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snacks/edit.html.erb
<h1>Editing snack</h1>

<%= render 'form' %>

<%= link_to 'Show', @snack %> |
<%= link_to 'Back', snacks_path %>

app/views/snacks/index.html.erb
<h1>Listing snacks</h1>

<table>
  <tr>
    <th>Healthy</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snacks.each do |snack| %>
  <tr>
    <td><%= snack.healthy %></td>
    <td><%= snack.description %></td>
    <td><%= link_to 'Show', snack %></td>
    <td><%= link_to 'Edit', edit_snack_path(snack) %></td>
    <td><%= link_to 'Destroy', snack, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snack', new_snack_path %>

app/views/snacks/new.html.erb
<h1>New snack</h1>

<%= render 'form' %>

<%= link_to 'Back', snacks_path %>

app/views/snacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Healthy:</b>
  <%= @snack.healthy %>
</p>

<p>
  <b>Description:</b>
  <%= @snack.description %>
</p>


<%= link_to 'Edit', edit_snack_path(@snack) %> |
<%= link_to 'Back', snacks_path %>